/*
  Automatically generated by 'make config' -- don't edit!
*/
#ifndef _PCMCIA_CONFIG_H
#define _PCMCIA_CONFIG_H

#define AUTOCONF_INCLUDED

#define LINUX "/usr/src/linux"
#define PREFIX ""
#define MODDIR "/lib/modules/2.2.5-15"
#define CC "gcc"
#define LD "ld"
#define PCDEBUG ""
#define KFLAGS ""
#define UFLAGS ""
#undef  UNSAFE_TOOLS
#undef  CONFIG_CARDBUS

/* Options from current kernel */
#undef  CONFIG_SMP
#define CONFIG_PCI 1
#define CONFIG_PCI_QUIRKS 1
#define CONFIG_APM 1
#define CONFIG_SCSI 1
#define CONFIG_INET 1
#define CONFIG_NET_RADIO 1
#define CONFIG_TR 1
#define CONFIG_MODVERSIONS 1
#define CONFIG_PROC_FS 1
#define CONFIG_ISA 1

#define UTS_RELEASE "2.2.5-15"
#define UTS_VERSION "#1 Mon Apr 19 23:00:46 EDT 1999"
#define LINUX_VERSION_CODE 131589

#define NEW_QLOGIC 1
#define HAS_PROC_BUS 1
#define HAS_WIRELESS_EXTENSIONS 1
#define SYSV_INIT 1
#undef  INSTALL_DEPMOD
#undef  HAS_FORMS

#endif /* _PCMCIA_CONFIG_H */
